### ISSUE TITLE
建议增加cdn.jsdelivr.net加速，还有token保持的功能

### ISSUE THREAD

**Issue by Rabbit2108** [netnr/mix#1]
建议增加cdn.jsdelivr.net加速，还有token保持的功能

**Comment by netnr** [comment]
你说的是哪个项目

**Comment by Rabbit2108** [comment]
> 你说的是哪个项目
GitStorage

**Comment by Rabbit2108** [comment]
> 你说的是哪个项目

额，token保持可以保持啊，不过还是加个cdn.jsdelivr.net加速比较好

**Comment by netnr** [comment]
是的

**Comment by netnr** [comment]
已经更新了

**Comment by Rabbit2108** [comment]
> 已经更新了

文件数量限制在哪里修改啊?

**Comment by netnr** [comment]
配置是在初始化上传控件设定的，不开放修改；目前数量限制为 500，单张为 5M

**Comment by Rabbit2108** [comment]
> 已经更新了

是我的出错了无法上传 https://pic4.58cdn.com.cn/nowater/webim/big/n_v22778b53b3df14011b3c9b8a086ec97ab.jpg

**Comment by Rabbit2108** [comment]
> 配置是在初始化上传控件设定的，不开放修改；目前数量限制为 500，单张为 5M

而且用你演示图床批量传了一下，html要一个个去复制吗？有点麻烦啊

**Comment by netnr** [comment]
你可以按自己的需求调整源码再部署

**Comment by Rabbit2108** [comment]
> 你可以按自己的需求调整源码再部署

部署好了，可是不能上传

**Comment by Rabbit2108** [comment]
> 你可以按自己的需求调整源码再部署

好气
